# List of conda and pip packages that are should be install when developing the packages
# To create the full conda environment: conda env create -f environment.yml
name: esa_cci_sm
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - netcdf4
  - pyresample
  - pip
  - pip:
    - pygeobase
    - pynetcf
    - repurpose
    - parse
    - configparser
    - smecv-grid==0.2.1
    - pygeogrids==0.3.0
    - more_itertools
